name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install frontend modules
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run frontend GUI tests 🧪
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:backend, npm run start:frontend
          command: npm run cy:run
